plugins {
    id 'java'
    id("io.qameta.allure") version "2.12.0"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation 'org.seleniumhq.selenium:selenium-java:4.31.0'

    // API client

    testImplementation 'io.rest-assured:rest-assured:5.5.1'
    implementation 'io.rest-assured:rest-assured-common:5.5.1'

    // report
    testImplementation 'io.qameta.allure:allure-junit5:2.29.1'
    runtimeOnly 'org.aspectj:aspectjweaver:1.9.24'
}

test {
    useJUnitPlatform()
}